= Cloud SDK pass:[<br/>] Console Access Library pass:[<br/>] TypeScript版 pass:[<br/>] 機能仕様書 pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc: AITRIOS™、およびそのロゴは、ソニーグループ株式会社またはその関連会社の登録商標または商標です。
:toc:
:toc-title: 目次
:toclevels: 1
:chapter-label:
:lang: ja

== 更新履歴

|===
|Date |What/Why
|2022/11/16
|初版作成

|2023/01/30
|version 0.2.0 修正対応 +
表現統一 +
PDFビルド環境更新

|2023/05/26
|version 1.0.0 修正対応

|2023/12/22
|version 1.1.0 修正対応 +
Console Enterprise Edition対応

|2023/03/26
|version 1.2.0 修正対応

|===

== はじめに

* 本書は、「**Console**」へのアクセスを提供する「**Console Access Library**」についての機能仕様である。 +
機能開発言語には、TypeScriptを使用する。

== 用語・略語
|===
|Terms/Abbreviations |Meaning 

|「**Console for AITRIOS**」
|エッジからクラウドを含めたソリューションを効率的に導入するための各種機能（デプロイメント機能、リトレーニング機能、エッジデバイスマネジメント機能など）を提供するクラウドサービス +
以降、本文中では「**Console**」と記載する

|「**Low Level SDK**」
|「**Console**」のREST APIのAPI仕様（yaml）からOpenAPI Generatorで自動生成したClient

|「**Cloud App**」
|「**Console Access Library**」を使用するアプリケーション

|SAS
|Shared Access Signatures +
Azure Storage リソースへの制限付きアクセス権を付与する URI

|
|

|===

== 想定ユースケース
* 「**Console Access Library**」を使用して、下記を実施する
** エッジデバイスの情報を取得
** エッジデバイスに推論開始（推論結果アップロード開始）、推論停止（推論結果アップロード停止）
** エッジデバイスの出力結果（画像、推論結果）の取得
** ユーザーが自分で作成したAIモデルを「**Console**」にアップロード
*** アップロードしたAIモデルの確認と削除
** AIモデルをエッジデバイスにデプロイ可能な形式に変換
** AIモデルをエッジデバイスにデプロイ
** ユーザーが自分で作成した「**DeviceApp**」を「**Console**」にアップロード
*** アップロードした「**DeviceApp**」の確認と削除
** 「**DeviceApp**」をエッジデバイスにデプロイ

== 機能概要、アルゴリズム
[#_Functional-Overview]
=== Functional Overview
* 「**Console**」にアクセス可能なClientを生成する
** 「**Console**」へのアクセスに必要な情報をConfigに設定し、ConfigをClientに設定する
+
「**Console**」へのアクセスに必要な情報は下記である
+
|===
|Name |Description

|Console endpoint
|APIサーバ・ベースURL

|Authorization endpoint
|アクセストークンを発行する認証サーバURL

|Client ID
|アクセストークン発行に必要なClient ID

|Client Secret
|アクセストークン発行に必要なClient Secret

|Application ID +
 (「**Console Enterprise Edition**」利用時に必要)
|アクセストークン発行に必要なApplication ID

|===

* Clientから機能毎に分類された「**Console**」のAPIを実行する
+
[TIP]
====
機能毎の分類は、「**Console**」が提供する「**Low Level SDK**」のAPIの分類に従います。 +
「**Console**」へのアクセスに必要なアクセストークンの取得と更新をします。（Wrap）
====
+
[TIP]
====
APIにtimeoutの引数がない場合にはtimeoutしない。
====
** DeviceManagement
*** getDevices / エッジデバイスの情報一覧取得
*** startUploadInferenceResult / 推論結果メタデータ取得開始
*** stopUploadInferenceResult / 推論結果メタデータ取得停止
*** getCommandParameterFile / 「**Console**」に登録されたcommand parameter fileの一覧取得
** AIモデル
*** importBaseModel / ベースモデルのインポート
*** getModels / モデル情報一覧取得
*** getBaseModelStatus / ベースモデル情報取得
*** deleteModel / モデル削除
*** publishModel / モデル発行
** Deployment
*** importDeviceApp / 「**DeviceApp**」のインポート
*** getDeviceApps / 「**DeviceApp**」の情報一覧取得
*** deleteDeviceApp / 「**DeviceApp**」の削除
*** getDeployConfigurations / デプロイconfig情報一覧取得
*** createDeployConfiguration / デプロイconfig情報登録
*** deployByConfiguration / デプロイ
*** getDeployHistory / デプロイ履歴取得
*** deleteDeployConfiguration / デプロイconfig情報削除
*** cancelDeployment / デプロイ状態強制キャンセル
*** deployDeviceApp / 「**DeviceApp**」のデプロイ
*** undeployDeviceApp / 「**DeviceApp**」のアンデプロイ
*** getDeviceAppDeploys / 「**DeviceApp**」のデプロイ履歴取得
** Insight
*** getImageDirectories / 画像保存ディレクトリ一覧取得
*** getImages / 保存済み画像取得
*** getInferenceResults / 保存済み推論結果メタデータ一覧取得
*** exportImages / 保存済み画像エクスポート

* 「**Low Level SDK**」のAPIをユースケースでまとめたHigh Level APIを実行できます。
** AIモデル
*** publishModelWaitResponse / モデル発行し、完了待ち
** Deployment
*** deployByConfigurationWaitResponse / デプロイし、完了待ち
*** deployDeviceAppWaitResponse / 「**DeviceApp**」をデプロイし、完了待ち
** Insight
*** getImageData / 保存済み画像取得
**** getImagesは、最大256件取得のため、本APIはgetImagesを複数回呼び出し、制限を隠蔽
*** getLastInferenceData / 保存済み推論結果の最新データ取得
*** getLastInferenceAndImageData / 保存済み推論結果と画像の最新データ取得
**** Dateの最も新しい画像を取得し、画像に紐づく推論結果を探して返却

* 「**Console Access Library**」の実行時、コンソールにログの出力を行う
** ログフォーマットは下記の通りに定義する
*** [ログ出力時刻] [ログレベル] [クライアント名] : メッセージ本文
*** ログ出力時刻は、ユーザーが利用する環境のシステム時刻を使用する
*** ログ出力時刻は、ISO 8601形式で日付+時刻+タイムゾーンを出力する
*** ログ出力例: +
2022-06-21T11:31:42.612+0900 ERROR ConsoleAccessClient : Failed to log request

** ログレベルを指定して、出力するログレベルを切り替えられる
*** ログレベルは下記の通りに定義する
+
[%header%autowidth]
|===
|Level |Summary 

|ERROR
|「**Console Access Library**」の実行時、正常に処理を終了できなかった場合に使用する

|WARNING
|異常とは言い切れないが正常とも異なる、何らかの予期しない問題が発生したときに使用する

|INFO
|「**Console Access Library**」がイベントを実行する際に使用する

|DEBUG
|「**Console Access Library**」の動作状況等、詳細なデバッグ情報を使用する

|OFF
|全てのログを無効にする
|===
*** 指定したログレベル以上のログを出力する +
例) INFOを指定するとINFO/WARNING/ERRORを出力し、DEBUGは出力しない
*** 指定したログレベルがOFFの場合は、全てのログレベルを出力しない
*** 既定のログレベルはOFFとする
*** ログレベルの指定は、ライブラリを利用するアプリケーション側で開発言語毎に指定された手順で行う
+
[%header]
|===
|TypeScriptでの指定例
a|
[source,TypeScript]
----
import { Logger } from 'consoleaccesslibrary';

# Set the desired logging level
Logger.setLogLevel("warning")
----
|===

* 「**Console Access Library**」の実行時、エラー条件の確認を行う
** 下記の条件でエラーと判断する
*** APIの入力パラメータが不適
*** APIの入力パラメータは適切だが、 「**Low Level SDK**」からの応答が期待通りではない(Timeout/Errorなど)
*** 「**Console**」に正常に接続できない(認証エラー、URL誤り、など)

=== Algorithm
* 「**Console Access Library**」使用開始
. 「**Cloud App**」でConfigを作成
+
. 「**Cloud App**」からのClientを作成
+
Client生成時には、アクセストークンの取得、「**Low Level SDK**」の生成
. Client instanceから「**Low Level SDK**」のAPIをWrapしたAPI、機能複合したAPI（High Level API）を利用
+
「**Low Level SDK**」のAPIをWrapしたAPI内で、「**Console**」へのアクセスに必要なアクセストークンの取得、更新
+
- ConfigにApplication IDが渡された場合、Microsoft Authentication Libraryによるトークンの取得、更新
- アクセストークンの有効期限は1時間となっており、有効期限が残り180秒以下の場合、アクセストークンの更新

* 推論結果メタデータ取得開始 - 停止
. getDevices APIで、エッジデバイスのIDを確認
. startUploadInferenceResult APIで推論結果メタデータ取得開始
. InsightのAPIを使用して、推論結果、画像の取得
. stopUploadInferenceResult APIで推論結果メタデータ取得停止


=== Under what condition
* 「**Console**」のAPIへのアクセスは「**Low Level SDK**」を使用すること

=== API
* Config
** constructor(consoleEndpoint: string, portalAuthorizationEndpoint: string, clientId: string, clientSecret: string, applicationId: string)

* Client
** constructor(configuration: Config)
** deviceManagement()
** aiModel()
** deployment()
** insight()

* DeviceManagement
** getDevices(deviceId?: string, deviceName?: string, connectionState?: string, deviceGroupId?: string, deviceIds?: string, scope?: string)
** startUploadInferenceResult(deviceId: string)
** stopUploadInferenceResult(deviceId: string)
** getCommandParameterFile()

* AIモデル
** importBaseModel(modelId: string, model: string, converted?: boolean, vendorName?: string, comment?: string, inputFormatParam?: string, networkConfig?: string, networkType?: string, metadataFormatId?: string)
** getModels(modelId?: string, comment?: string, projectName?: string, modelPlatform?: string, projectType?: string, deviceId?: string, latestType?: string)
** getBaseModelStatus(modelId: string, latestType?: string)
** deleteModel(modelId: string)
** publishModel(modelId: string, deviceId?: string)

* AIモデル High Level API
** publishModelWaitResponse(modelId: string, deviceId?: string, callback?: publishModelWaitResponseCallback)
*** publishModelWaitResponseCallback(status: string)

* Deployment
** importDeviceApp(compiledFlg: string, appName: string, versionNumber: string, fileName: string, fileContent: string, entryPoint?: string, comment?: string, schemaInfo?: object)
** getDeviceApps()
** deleteDeviceApp(appName: string, versionNumber: string)
** getDeployConfigurations()
** createDeployConfiguration(configId: string, comment?: string, sensorLoaderVersionNumber?: string, sensorVersionNumber?: string, modelId?: string, modelVersionNumber?: string, apFwVersionNumber?: string)
** deployByConfiguration(configId: string, deviceIds: string, replaceModelId?: string, comment?: string)
** getDeployHistory(deviceId: string)
** deleteDeployConfiguration(configId: string)
** cancelDeployment(deviceId: string, deployId: string)
** deployDeviceApp(appName: string, versionNumber: string, deviceIds: string, comment?: string)
** undeployDeviceApp(deviceIds: string)
** getDeviceAppDeploys(appName: string, versionNumber: string)

* Deployment High Level API
** deployByConfigurationWaitResponse(configId: string, deviceIds: string, replaceModelId?: string, comment?: string, timeout?: number, callback?: deployByConfigurationWaitResponseCallback)
*** deployByConfigurationWaitResponseCallback(deviceStatusArray: object)
** deployDeviceAppWaitResponse(appName: string, versionNumber: string, deviceIds: string, comment?: string, callback?: deployDeviceAppWaitResponseCallback)
*** deployDeviceAppWaitResponseCallback(deviceStatusArray: object)

* Insight
** getImageDirectories(deviceId?: string)
** getImages(deviceId: string, subDirectoryName: string, numberOfImages?: number, skip?: number, orderBy?: string, fromDatetime?: string, toDatetime?: string)
** getInferenceResults(deviceId: string, filter?: string, numberOfInferenceResults?: number, raw?: number, time?: string)
** exportImages(key: string, fromDatetime?: string, toDatetime?: string, deviceId?: string, fileFormat?: string)

* Insight High Level API
** getImageData(deviceId: string, subDirectoryName: string, numberOfImages?: number, skip?: number, orderBy?: string, fromDatetime?: string, toDatetime?: string)
** getLastInferenceData(deviceId: string)
** getLastInferenceAndImageData(deviceId: string, subDirectoryName: string)

=== Others Exclusive conditions / specifications
* command parameter fileをエッジデバイスに適用済みであること

== 操作性仕様、画面仕様
* なし

== APIパラメータ
各エラーメッセージは、関数名が言語によって異なる（この資料では代表してTypeScriptでのエラーメッセージを記載）

* Config
** constructor: コンストラクタ
+
【Error：consoleEndpointが空の場合】E001 : consoleEndpoint is required.
+
【Error：portalAuthorizationEndpointが空の場合】E001 : portalAuthorizationEndpoint is required.
+
【Error：clientIdが空の場合】E001 : clientId is required.
+
【Error：clientSecretが空の場合】E001 : clientSecret is required.
+
|===
|Parameter’s name|Meaning|Range of parameter

|consoleEndpoint
|「**Console**」へのアクセス先URL
|なし +
指定なしの場合、環境変数から読み出す

|portalAuthorizationEndpoint
|「**Console**」へのアクセスに必要なアクセストークン発行先URL
|なし +
指定なしの場合、環境変数から読み出す

|clientId
|アクセストークン発行に必要なClient ID
|なし +
指定なしの場合、環境変数から読み出す

|clientSecret
|アクセストークン発行に必要なClient Secret
|なし +
指定なしの場合、環境変数から読み出す

|application_id
|アクセストークン発行に必要なApplication ID
|なし +
指定なしの場合、環境変数から読み出す

|===
+
|===
|Return value|Meaning

|Config instance
|「**Console**」へのアクセスに必要な情報を保持したconfig instance
|===

* Client
** constructor: コンストラクタ
+
|===
|Parameter’s name|Meaning|Range of parameter

|configuration
|「**Console**」へのアクセスに必要な情報を保持したconfig instance
|なし

|===
+
|===
|Return value|Meaning

|Client instance
|「**Low Level SDK**」のAPIをWrapしたAPI、機能複合したAPI（High Level API）を実行可能なclient instance
|===

** deviceManagement: DeviceManagement APIを提供するInstanceの取得
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|DeviceManagement instance
|DeviceManagement APIを提供するInstance
|===

** aiModel: AIモデル APIを提供するInstanceの取得
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|AIモデル instance
|AIモデル APIを提供するInstance
|===

** deployment: Deployment APIを提供するInstanceの取得
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|Deployment instance
|Deployment APIを提供するInstance
|===

** insight: Insight APIを提供するInstanceの取得
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|Insight instance
|Insight APIを提供するInstance
|===

* DeviceManagement
** getDevices: エッジデバイスの情報一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|部分検索、大文字小文字は区別しない +
指定なしの場合、全deviceId検索

|deviceName
|エッジデバイスの名前
|部分検索、大文字小文字は区別しない +
指定なしの場合、全deviceName検索

|connectionState
|接続状態
|接続状態の場合: Connected +
切断状態の場合: Disconnected +
完全一致検索、大文字小文字は区別しない +
指定なしの場合、全connectionState検索

|deviceGroupId
|エッジデバイスの所属グループ
|完全一致検索、大文字小文字は区別しない +
指定なしの場合、全deviceGroupId検索

|deviceIds
|エッジデバイスの所属グループ
|複数のDevice IDをカンマで区切って指定 +
指定なしの場合、全deviceIds検索

|scope
|エッジデバイスの所属グループ
|レスポンスパラメータの範囲を指定 +
設定値 +
full: 完全なパラメータを返す +
minimal: 最小限のパラメータを返す(応答速度が速い) +
指定なしの場合、全scope検索

|===
+
|===
|Return value|Meaning

|Edge Device information
|エッジデバイスの情報
|===

** startUploadInferenceResult: 推論結果メタデータ取得開始
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|result
|実行結果

|outputSubDirectory
|Input Image格納パス、UploadMethod:Blob Storageのみ

|outputSubDirectoryIR
|Input Inference格納パス、UploadMethodIR:Blob Storageのみ

|===

** stopUploadInferenceResult: 推論結果メタデータ取得停止
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** getCommandParameterFile:  「**Console**」に登録されたcommand parameter fileの一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|result
|「**Console**」に登録されているCommandParameterの一覧

|===

* AIモデル
** importBaseModel: ベースモデルのインポート
+
【Error：modelIdが空の場合】E001 : modelId is required.
+
【Error：modelが空の場合】E001 : model is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|モデルID(新規保存またはバージョンアップ対象のモデルID)
|100文字以内 +
下記以外は禁則文字 +
半角英数字 +
- ハイフン +
_ アンダーバー +
() 小括弧 +
. ドット

|model
|モデルファイル  SAS URI
|なし

|converted
|変換済みフラグ
|True: 変換後モデル +
False: 変換前モデル +
指定なしの場合、False

|vendorName
|ベンダー名（新規保存の場合に指定）
|100文字以内 +
バージョンアップの場合指定しない +
指定なしの場合、ベンダー名なし

|comment
|モデルを新規登録する際に入力するモデルに関する説明 +
新規保存時はモデルとバージョンの説明として設定される +
バージョンアップ時はバージョンの説明として設定される
|100文字以内
指定なしの場合、モデルを新規登録する際に入力するモデルに関する説明なし

|inputFormatParam
|input format paramファイル（json形式）のURI +
下記について評価を実施 +
 Azure：SAS URI +
 AWS：  Presigned URI +
用途：Packagerの変換情報(image format情報)
|SAS URI形式以外は禁則文字 +
jsonの形式はオブジェクトの配列(各オブジェクトは下記値を含む) +
例 +
ordinal: コンバータへのDNN入力の順序（値範囲：0～2） +
format: フォーマット（"RGB" or "BGR"） +
指定なしの場合、評価しない

|networkConfig
|network config ファイル（json形式）のURI +
下記について評価を実施 +
 Azure：SAS URI +
 AWS：  Presigned URI +
変換前モデルの場合、指定する(=変換後モデルの場合、無視する) +
用途：model converterの変換パラメータ情報
|SAS URI形式以外は禁則文字 +
指定なしの場合、評価しない

|networkType
|ネットワーク種別(モデル新規登録の場合のみ有効)
|0：Custom Vision +
1：Non Custom Vision +
指定なしの場合、1


|metadataFormatId
|メタデータ形式ID
|100文字以内

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** getModels: モデル情報一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|モデルID
|部分検索 +
指定なしの場合、全modelId検索

|comment
|モデル説明
|部分検索 +
指定なしの場合、全comment検索

|projectName
|プロジェクト名
|部分検索 +
指定なしの場合、全projectName検索

|modelPlatform
|モデルプラットフォーム
|0 : Custom Vision +
1 : Non Custom Vision +
2 : Model Retrainer +
完全一致検索 +
指定なしの場合、全modelPlatform検索

|projectType
|プロジェクト種別
|0 : ベース +
1 : エッジデバイス +
完全一致検索 +
指定なしの場合、全projectType検索

|deviceId
|エッジデバイスのID(デバイスモデルを検索したい場合に指定)
|完全一致検索 +
大文字小文字を区別する +
指定なしの場合、全deviceId検索

|latestType
|最新バージョン種別
|0 : 発行済み最新バージョン +
1 : 最新バージョン(変換/発行処理中モデルバージョンも含めた最新) +
完全一致検索 +
指定なしの場合、1

|===
+
|===
|Return value|Meaning

|Model information
|モデル情報

|===

** getBaseModelStatus: ベースモデル情報取得
+
【Error：modelIdが空の場合】E001 : modelId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|モデルID
|なし

|latestType
|最新バージョン種別
|0 : 発行済み最新バージョン +
1 : 最新バージョン(変換/発行処理中モデルバージョンも含めた最新) +
完全一致検索 +
指定なしの場合、1

|===
+
|===
|Return value|Meaning

|Base Model information
|ベースモデル情報

|===

** deleteModel: モデル削除
+
【Error：modelIdが空の場合】E001 : modelId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|モデルID
|なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** publishModel: モデル発行
+
【Error：modelIdが空の場合】E001 : modelId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|モデルID
|なし

|deviceId
|エッジデバイスのID
|大文字小文字を区別する +
デバイスモデルが対象の場合に指定する +
ベースモデルが対象の場合、指定しない

|===
+
|===
|Return value|Meaning

|result
|実行結果

|importId
|インポートID

|===

** publishModelWaitResponse: モデル発行し、完了待ち
+
【Error：modelIdが空の場合】E001 : modelId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|モデルID
|なし

|deviceId
|エッジデバイスのID
|大文字小文字を区別する +
デバイスモデルが対象の場合に指定する +
ベースモデルが対象の場合、指定しない

|callback
|コールバック関数
|getBaseModelStatusで処理結果確認し、コールバック関数を呼び出して処理状況通知 +
指定なしの場合、コールバック通知なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|process time
|処理時間

|===

** publishModelWaitResponseCallback: publishModelWaitResponseの状態通知Callback
+
|===
|Parameter’s name|Meaning|Range of parameter

|status
|Publish状態
|'01': 'Before conversion' +
'02': 'Converting' +
'03': 'Conversion failed' +
'04': 'Conversion complete' +
'05': 'Adding to configuration' +
'06': 'Add to configuration failed' +
'07': 'Add to configuration complete' +
'11': 'Saving'(Model Retrainerの場合のモデル保存中ステータス)

|===
+
|===
|Return value|Meaning

|-
|-

|===

* Deployment
** importDeviceApp: 「**DeviceApp**」インポート
+
【Error：compiledFlgが空の場合】E001 : compiledFlg is required.
+
【Error：appNameが空の場合】E001 : appName is required.
+
【Error：versionNumberが空の場合】E001 : versionNumber is required.
+
【Error：fileNameが空の場合】E001 : fileName is required.
+
【Error：fileContentが空の場合】E001 : fileContent is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|compiledFlg
|コンパイルフラグ
|0:未コンパイル(コンパイル処理を行う) +
1:コンパイル済み(コンパイル処理を行わない)

|appName
|「**DeviceApp**」名
|文字数上限は、appName + versionNumber <=31 とする +
下記以外は禁則文字 +
・英数字 +
・アンダーバー +
・ドット

|versionNumber
|「**DeviceApp**」バージョン
|文字数上限は、appName + versionNumber <=31 とする +
下記以外は禁則文字 +
・英数字 +
・アンダーバー +
・ドット

|fileName
|「**DeviceApp**」ファイル名
|なし

|fileContent
|「**DeviceApp**」ファイル内容
|Base64 Encodeされた文字列

|entryPoint
|「**EVPモジュール**」のエントリポイント
|なし +
指定なしの場合、"ppl"

|comment
|「**DeviceApp**」説明
|100文字以内 +
指定なしの場合、コメントなし

|schemaInfo
|スキーマ情報
|形式: +
const schemaInfo = +
 { interfaces: { in: [{ metadataFormatId: 'formatId' }] } }

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** getDeviceApps: 「**DeviceApp**」情報一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|DeviceApp information
|「**DeviceApp**」情報

|===

** deleteDeviceApp: 「**DeviceApp**」削除
+
【Error：appNameが空の場合】E001 : appName is required.
+
【Error：versionNumberが空の場合】E001 : versionNumber is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|appName
|「**DeviceApp**」名
|なし

|versionNumber
|「**DeviceApp**」バージョン
|なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** getDeployConfigurations: デプロイconfig情報一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|DeployConfiguration information
|DeployConfiguration情報

|===

** createDeployConfiguration: デプロイconfig情報登録
+
【Error：configIdが空の場合】E001 : configId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|configId
|config ID
|20文字以内 +
下記以外は禁則文字 +
半角英数字 +
- ハイフン +
_ アンダーバー +
() 小括弧 +
. ドット

|comment
|Config説明
|100文字以内 +
指定なしの場合、コメントなし

|sensorLoaderVersionNumber
|SensorLoaderバージョン番号
|-1を指定した場合、デフォルトバージョン(システム設定「DVC0017」)を適用 +
指定なしの場合SensorLoaderデプロイなし

|sensorVersionNumber
|Sensorバージョン番号
|-1を指定した場合、デフォルトバージョン(システム設定「DVC0018」)を適用 +
指定なしの場合Sensorデプロイなし

|modelId
|モデルID
|指定なしの場合、モデルデプロイなし

|modelVersionNumber
|モデルバージョン番号
|指定なしの場合、最新のVersionを適用

|apFwVersionNumber
|ApFwバージョン番号
|指定なしの場合、ファームウェアデプロイなし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** deployByConfiguration: デプロイ
+
【Error：configIdが空の場合】E001 : configId is required.
+
【Error：deviceIdsが空の場合】E001 : deviceIds is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|configId
|config ID
|なし

|deviceIds
|エッジデバイスのIDs
|カンマ区切りで複数のエッジデバイスのIDを指定 +
大文字小文字を区別する

|replaceModelId
|入替対象モデルID
|「modelId」または「networkId」を指定 +
指定されたモデルIDのものがDBに存在しない場合、入力された値をnetworkId(「**Console**」の内部管理ID)としてみなし、処理を行う +
指定なしの場合、入替しない.

|comment
|デプロイコメント
|100文字以内 +
指定なしの場合、コメントなし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** getDeployHistory: デプロイ履歴取得
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|deploy history
|デプロイ履歴

|===

** deleteDeployConfiguration: デプロイconfig情報削除
+
【Error：configIdが空の場合】E001 : configId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|configId
|config ID
|なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** cancelDeployment: デプロイ状態強制キャンセル
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：deployIdが空の場合】E001 : deployId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|deployId
|デプロイID
|getDeployHistoryで取得出来るid

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** deployDeviceApp: 「**DeviceApp**」デプロイ
+
【Error：appNameが空の場合】E001 : appName is required.
+
【Error：versionNumberが空の場合】E001 : versionNumber is required.
+
【Error：deviceIdsが空の場合】E001 : deviceIds is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|appName
|App名
|なし

|versionNumber
|Appバージョン
|なし

|deviceIds
|エッジデバイスのIDs
|カンマ区切りで複数のエッジデバイスのIDを指定 +
大文字小文字を区別する

|comment
|デプロイコメント
|100文字以内 +
指定なしの場合、コメントなし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** undeployDeviceApp: 「**DeviceApp**」アンデプロイ
+
【Error：deviceIdsが空の場合】E001 : deviceIds is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceIds
|エッジデバイスのID
|カンマ区切りで複数のエッジデバイスのIDを指定 +
大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** getDeviceAppDeploys: 「**DeviceApp**」デプロイ履歴取得
+
【Error：appNameが空の場合】E001 : appName is required.
+
【Error：versionNumberが空の場合】E001 : versionNumber is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|appName
|App名
|なし

|versionNumber
|Appバージョン
|なし

|===
+
|===
|Return value|Meaning

|DeviceApp deploy history
|「**DeviceApp**」デプロイ履歴

|===

** deployByConfigurationWaitResponse: デプロイし、完了待ち
+
【Error：configIdが空の場合】E001 : configId is required.
+
【Error：deviceIdsが空の場合】E001 : deviceIds is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|configId
|config ID
|なし

|deviceIds
|エッジデバイスのIDs
|カンマ区切りで複数のエッジデバイスのIDを指定 +
大文字小文字を区別する

|replaceModelId
|入替対象モデルID
|「modelId」または「networkId」を指定 +
指定されたモデルIDのものがDBに存在しない場合、入力された値をnetworkId(「**Console**」の内部管理ID)としてみなし、処理を行う +
指定なしの場合、入替しない.

|comment
|デプロイコメント
|100文字以内 +
指定なしの場合、コメントなし

|timeout
|完了待ちのtimeout時間 +
デプロイ処理でエッジデバイスがハングアップするなどで、処理中のままとなるケースがあるため、処理を抜けるtimeout
|なし +
指定なしの場合、3600秒

|callback
|コールバック関数 +
getDeployHistoryで処理結果確認し、コールバック関数を呼び出して処理状況通知
|指定なしの場合、コールバック通知なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|process time
|処理時間

|===

** deployByConfigurationWaitResponseCallback: deployByConfigurationWaitResponseの状態通知Callback
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceStatusArray
|エッジデバイスのDeploy状態リスト
|下記形式 +
[ +
　{ +
　　<deviceId>: { +
　　　"status":<status> +
　　} +
　}, +
] +

deployByConfigurationWaitResponseのdeviceIdsで指定したdeviceId分のデータが入る +

<deviceId>: エッジデバイスのID +
<status>: 下記のデプロイ状態を格納 +
　0：デプロイ中 +
　1：正常終了 +
　2：失敗 +
　3：キャンセル +
　9：「**DeviceApp**」アンデプロイ

|===
+
|===
|Return value|Meaning

|-
|-

|===

** deployDeviceAppWaitResponse: 「**DeviceApp**」デプロイし、完了待ち
+
【Error：appNameが空の場合】E001 : appName is required.
+
【Error：versionNumberが空の場合】E001 : versionNumber is required.
+
【Error：deviceIdsが空の場合】E001 : deviceIds is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|appName
|App名
|なし

|versionNumber
|Appバージョン
|なし

|deviceIds
|エッジデバイスのIDs
|カンマ区切りで複数のエッジデバイスのIDを指定 +
大文字小文字を区別する

|comment
|デプロイコメント
|100文字以内 +
指定なしの場合、コメントなし

|callback
|コールバック関数 +
getDeviceAppDeploysで処理結果確認し、コールバック関数を呼び出して処理状況通知
|指定なしの場合、コールバック通知なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|process time
|処理時間

|===

** deployDeviceAppWaitResponseCallback: deployDeviceAppWaitResponseの状態通知Callback
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceStatusArray
|エッジデバイスのDeploy状態リスト
|下記形式 +
[ +
　{ +
　　<deviceId>: { +
　　　"status":<status>, +
　　　"found_position":<found_position>, +
　　　"skip":<skip> +
　　} +
　}, +
] +

deployDeviceAppWaitResponseのdeviceIdsで指定したdeviceId分のデータが入る +

<deviceId>: エッジデバイスのID +
<found_position>: getDeviceAppDeploysレスポンスに格納されるdeviceIdのindex +
<skip>: 下記の値を格納 +
　0: getDeviceAppDeploysレスポンスに格納される最新のstatusの場合 +
　1: getDeviceAppDeploysレスポンスに格納される最新以外のstatusの場合 +
<status>: 下記のデプロイ状態を格納 +
　0：デプロイ中 +
　1：正常終了 +
　2：失敗 +
　3：キャンセル +

|===
+
|===
|Return value|Meaning

|-
|-

|===

* Insight
** getImageDirectories: 画像保存ディレクトリ一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する +
指定なしの場合、全てのdeviceIdの情報を返す

|===
+
|===
|Return value|Meaning

|Image save directory information
|画像保存ディレクトリ情報
|===

** getImages: 保存済み画像取得
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：subDirectoryNameが空の場合】E001 : subDirectoryName is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|subDirectoryName
|画像保存のサブディレクトリ
|なし +
サブディレクトリは、startUploadInferenceResultの応答で通知されるdirectory、または、getImageDirectoriesで取得したdirectory

|numberOfImages
|画像の取得数
|0-256 +
指定なしの場合:50

|skip
|取得をスキップする画像の数
|なし +
指定なしの場合:0

|orderBy
|ソート順：画像の作成された日時によるソート順
|DESC、ASC、desc、asc +
指定なしの場合:ASC

|fromDatetime
|日時(From)
|yyyyMMddhhmm形式 +
指定なしの場合、Fromの範囲設定なし

|toDatetime
|日時(To)
|yyyyMMddhhmm形式 +
指定なしの場合、Toの範囲設定なし

|===
+
|===
|Return value|Meaning

|Total image count
|全画像数

|Image filename and image content
|画像ファイル名と、画像ファイルデータ（Base64 Encode済みデータ）
|===

** getInferenceResults: 保存済み推論結果メタデータ一覧取得
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|filter
|検索フィルタ(AzureポータルのCosmos DB UIと下記以外は同じ仕様) +
- where文字列を先頭に付加する必要はない +
- deviceIdを付加する必要はない
|なし

|numberOfInferenceResults
|取得件数
|なし +
指定なしの場合:20

|raw
|推論結果のデータ形式
|1:Cosmos DBに格納されたままのレコードを付加 +
0:付与しない +
指定なしの場合:1

|time
|Cosmos DBに格納された推論結果データのタイムスタンプ
|yyyyMMddHHmmssfff +
- yyyy: 4桁の年の文字列 +
- MM: 2桁の月の文字列 +
- dd: 2桁の日の文字列 +
- HH: 2桁の時間の文字列 +
- mm: 2桁の分の文字列 +
- ss: 2桁の秒の文字列 +
- fff: 3桁のミリ秒の文字列

|===
+
|===
|Return value|Meaning

|inference data
|推論結果
|===

** exportImages: 保存済み画像エクスポート
+
【Error：keyが空の場合】E001 : key is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|key
|RSA公開鍵
|Base64 Encodeされた文字列

|fromDatetime
|日時(From)
|yyyyMMddhhmm形式 +
指定なしの場合、Fromの範囲設定なし

|toDatetime
|日時(To)
|yyyyMMddhhmm形式 +
指定なしの場合、Toの範囲設定なし

|deviceId
|エッジデバイスのID
|大文字小文字を区別する +
指定なしの場合、全deviceId指定

|fileFormat
|画像ファイルフォーマット
|JPG、BMP、RAW +
指定しない場合、絞り込みなし

|===
+
|===
|Return value|Meaning

|key
|共通鍵 +
公開鍵で暗号化された画像復号化用の共通鍵

|url
|ダウンロード用のSUS URI

|===

** getImageData: 保存済み画像取得
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：subDirectoryNameが空の場合】E001 : subDirectoryName is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|subDirectoryName
|画像保存のサブディレクトリ
|なし +
サブディレクトリは、startUploadInferenceResultの応答で通知されるdirectory、または、getImageDirectoriesで取得したdirectory

|numberOfImages
|画像の取得数
|なし +
指定なしの場合:50

|skip
|取得をスキップする画像の数
|なし +
指定なしの場合:0

|orderBy
|ソート順：画像の作成された日時によるソート順
|DESC、ASC、desc、asc +
指定なしの場合:ASC

|fromDatetime
|日時(From)
|yyyyMMddhhmm形式 +
指定なしの場合、Fromの範囲設定なし

|toDatetime
|日時(To)
|yyyyMMddhhmm形式 +
指定なしの場合、Toの範囲設定なし

|===
+
|===
|Return value|Meaning

|Total image count
|全画像数

|Image filename and image content
|画像ファイル名と、画像ファイルデータ（Base64 Encode済みデータ）
|===

** getLastInferenceData: 保存済み推論結果の最新データ取得
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|inference data
|推論結果
|===

** getLastInferenceAndImageData(): 保存済み推論結果と画像の最新データ取得
+
【Error：deviceIdが空の場合】E001 : deviceId is required.
+
【Error：subDirectoryNameが空の場合】E001 : subDirectoryName is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|エッジデバイスのID
|大文字小文字を区別する

|subDirectoryName
|画像保存のサブディレクトリ
|なし +
サブディレクトリは、startUploadInferenceResultの応答で通知されるdirectory、または、getImageDirectoriesで取得したdirectory

|===
+
|===
|Return value|Meaning

|inference data and image data
|推論結果と画像データ（Base64 Encode済みデータ）
|===

== ログ出力メッセージ
レベル毎に表示するメッセージは下記の通り定義する

=== ERRORレベル
[%header%autowidth]
|===
|MessageID |Conditions |Message |Parameter
|E001
|必要な引数が渡されなかった際に出力される
|{0} is required.
|{0}:渡されなかった引数名
|===

=== WARNINGレベル
[%header%autowidth]
|===
|MessageID |Conditions |Message |Parameter
|W001
|非推奨になったクラスや関数を呼び出した際に出力される
|{0} has been deprecated.
|{0}:呼び出されたクラスや関数名
|===

=== INFOレベル
T.B.D.

=== DEBUGレベル
T.B.D.

== 目標性能
* なし

== 制限事項
* deployByConfigurationWaitResponse APIは、過去に同一のデプロイconfigを用いてデプロイを行った履歴があるデバイスの場合、過去の結果を返却することがあります。 +
  その場合は、再度getDeployHistory APIを使用することでデプロイ処理状況を確認することができます。

== その他特記事項
* なし

== 未決定事項
* なし
