= Cloud SDK pass:[<br/>] Console Access Library pass:[<br/>] TypeScript pass:[<br/>] Tutorial pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc1: AITRIOS™ and AITRIOS logos are the registered trademarks or trademarks
:trademark-desc2: of Sony Group Corporation or its affiliated companies.
:toc:
:toc-title: TOC
:toclevels: 1
:chapter-label:
:lang: en

== Objective
To explain the various APIs exposed by "**Console Access Library**" and help the user to build and use the library.

== Prerequisites
The following is the required software you need to install in your system.

* VS Code
* Node >=v18
* Install TypeScript globally
** npm install -g typescript

=== "**Console Access Library**" API Specification
Please refer the below procedure regarding how to refer the "**Console Access Library**" API specifications. 

1. Clone the repository
    ** https://github.com/SonySemiconductorSolutions/aitrios-sdk-console-access-lib-ts

2.  Open `**docs/api-reference/index.html**` available in the cloned directory via browser

== Usage

=== Installation and Setup
The following is a step for installing and setting up "**Console Access Library**" sample application.

1. Clone the repository
    ** https://github.com/SonySemiconductorSolutions/aitrios-sdk-console-access-lib-ts.git
2. Open terminal and go to the `**lib/js-client**` path and run the following command
+ 
```
    npm install
    tsc -b
    npm pack
```

3. Open terminal and go to the `**src**` path and run the following command
+ 
```
    npm install
    tsc -b
    npm pack
```

4. Open terminal and go to the `**samples/demo-console**` path and run the following command
+ 
```
    npm install
```

=== Set configuration parameter to start "**Console Access Library**" sample application

* Create the following configuration file and set the parameters:
+
`samples/demo-console/console_access_settings.yaml`

|===
| When using "**Console Developer Edition**"
a|
[source,Yaml]
----
   console_access_settings:
     console_endpoint: "__console_endpoint__"
     portal_authorization_endpoint: "__portal_authorization_endpoint__"
     client_secret: "__client_secret__"
     client_id: "__client_id__"
----
|===

|===
| When using "**Console Enterprise Edition**"
a|
[source,Yaml]
----
   console_access_settings:
    console_endpoint: "__base_url__"
    portal_authorization_endpoint: "https://login.microsoftonline.com/'__tenant_id__'"
    client_secret: "__client_secret__"
    client_id: "__client_id__"
    application_id: "__application_id__"
----
|===

* Open the following file and change the parameters:
+
|===
|samples/demo-console/demo_config.yaml
a|
[source,Yaml]
----
  demo_configuration:
    device_id: "__device_id__"
    get_model_device_id: "__get_model_device_id__"
    publish_model_wait_response_device_id: "__publish_model_wait_response_device_id__"
    model_id: "__model_id__"
    model: "__model__"
    converted: "__converted__"
    vendor_name: "__vendor_name__"
    comment: "__comment__"
    input_format_param: "__input_format_param__"
    network_config: "__network_config__"
    network_type: "__network_type__"
    metadata_format_id: "__metadata_format_id__"
    project_name: "__project_name__"
    model_platform: "__model_platform__"
    project_type: "__project_type__"
    latest_type: "__latest_type__"
    config_id: "__config_id__"
    sensor_loader_version_number: "__sensor_loader_version_number__"
    sensor_version_number: "__sensor_version_number__"
    model_version_number: "__model_version_number__"
    ap_fw_version_number: "__ap_fw_version_number__"
    device_ids: "__device_ids__"
    replace_model_id: "__replace_model_id__"
    timeout: "__timeout__"
    compiled_flg: "__compiled_flg__"
    app_name: "__app_name__"
    version_number: "__version_number__"
    file_name: "__file_name__"
    entry_point: "__entry_point__"
    schema_info: "__schema_info__"
    device_name: "__device_name__"
    connection_state: "__connection_state__"  
    device_group_id: "__device_group_id__"
    scope: "__scope__"
    sub_directory_name: "__sub_directory_name__"
    number_of_images: "__number_of_images__"
    skip: "__skip__"
    order_by: "__order_by__"
    number_of_inference_results: "__number_of_inference_results__"
    filter: "__filter__"
    raw: "__raw__"
    time: "__time__"
----
|===

=== Network proxy setting

To use the "**Console Access Library**" in a proxy environment, set the `**https_proxy**` environment variable.

```
export https_proxy=http://username:password@proxyhost:port
```

=== Starting the App

To run the CLI demo, open cmd terminal from the  `**samples/demo-console**` folder, and run the following command.

```
npx ts-node index.ts
```

NOTE: When APIs are batch-executed in demo-console, it may fail due to the impact of the processing time of 
other APIs. In such case, execute the failed APIs separately.  +
When executing APIs individually, open samples/demo-console/src/controller/apiexecutor.ts and 
comment out the APIs that are not to be executed.

* Example:

|===
|samples/demo-console/src/controller/apiexecutor.ts
a|
[source,TypeScript]
----
        // DeviceManagement - StartUploadInferenceResult
        // try {
        //     response = 
        //          await client?.deviceManagement?.startUploadInferenceResult(deviceId);
        //     console.log('*********************************************');
        //     console.log('*********************************************');
        //     if ('data' in response) {
        //         response = JSON.stringify(response.data);
        //     } else {
        //         response = JSON.stringify(response)
        //     }
        //     console.log("StartUploadInferenceResult response: " + response);
        // } catch (e) {
        //     console.log("StartUploadInferenceResult Exception: " + e);
        // }
----
|===