= Cloud SDK pass:[<br/>] Console Access Library pass:[<br/>] TypeScript pass:[<br/>] Functional Specifications pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc1: AITRIOS™ and AITRIOS logos are the registered trademarks or trademarks
:trademark-desc2: of Sony Group Corporation or its affiliated companies.
:toc:
:toc-title: TOC
:toclevels: 1
:chapter-label:
:lang: en

== Change history

|===
|Date |What/Why 

|2022/11/16
|Initial draft

|2023/1/30
|Changed for Cloud SDK 0.2.0 +
Unified the swinging of expressions +
Updated the PDF build environment



|===

== Introduction

* This book is functional specifications for the Console Access Library that provides access to the Console. + 
Use TypeScript for feature development language.

== Terms/Abbreviations
|===
|Terms/Abbreviations |Meaning 

|Console for AITRIOS
|A cloud service that provides various functions (Deployment, Retraining, Edge AI Device Management etc.) to efficiently implement solutions from edge to cloud +
Hereafter referred to as Console in the text

|Low Level SDK
|Client generated automatically by OpenAPI Generator from the API specification (yaml) of the Console REST API

|Cloud App
|Applications that use the Console Access Library

|SAS
|Shared Access Signatures +
URI that grant limited access to Azure storage resources

|===

== Expected use case
* Use the Console Access Library to:
** Get information about edge AI devices
** Start inference (Start to upload inference results), stop inference (stop to upload inference results) of edge AI devices
** Get edge AI device output results (images, inference results)
** Upload AI models created by users to the Console
*** Review and delete uploaded AI models
** Convert AI models to a format deployable to edge AI devices
** Deploy AI models to edge AI devices
** Upload DeviceApps created by users to the Console
*** Review and delete uploaded DeviceApps
** Deploy DeviceApps to edge AI devices

== Functional overview/Algorithm
[#_Functional-Overview]
=== Functional overview
* Generate a Client accessible to the Console
** Set the information needed to access the Console in a Config, and set the Config to the Client
+
The information needed to access the Console is as follows
+
|===
|Name |Description

|Console endpoint
|API server/base URL

|Authorization endpoint
|URL of an authentication server that issues an access token

|Client ID
|Client ID needed to issue an access token

|Client Secret
|Client secret needed to issue an access token

|===

* Execute Console REST API classified by function from the Client
+
[TIP]
====
The functional classification follows the API classification of the Low Level SDK provided by the Console. + 
Get and update an access token needed to access the Console.（Wrap）
====
+
[TIP]
====
API without a timeout parameter will not timeout
====
** DeviceManagement
*** getDevices / Get edge AI device info list
*** startUploadInferenceResult / Start to upload inference results
*** stopUploadInferenceResult / Stop to upload inference results
*** getCommandParameterFile / Get list of command parameter files registered in the Console
** AI Model
*** importBaseModel / Import base model
*** getModels / Get model info list
*** getBaseModelStatus / Get base model status
*** deleteModel / Delete model
*** publishModel / Publish model
** Deployment
*** importDeviceApp / Import DeviceApp
*** getDeviceApps / Get DeviceApp info list
*** deleteDeviceApp / Delete DeviceApp
*** getDeployConfigurations / Get deployment configuration list
*** createDeployConfiguration / Create deployment configuration
*** deployByConfiguration / Deploy
*** getDeployHistory / Get deployment history
*** deleteDeployConfiguration / Delete deployment configuration
*** cancelDeployment / Force cancel deployment state
*** deployDeviceApp / Deploy DeviceApp
*** undeployDeviceApp / Undeploy DeviceApp
*** getDeviceAppDeploys / Get DeviceApp deployment history
** Insight
*** getImageDirectories / Get image save directory list
*** getImages / Get saved images
*** getInferenceResults / Get list of saved inference result metadata
*** exportImages / Export saved images

* High Level API that combine Low Level SDK API for each use case can be executed.
** AI Model
*** publishModelWaitResponse / Publish model and wait for response
** Deployment
*** deployByConfigurationWaitResponse / Deploy and wait for response
*** deployDeviceAppWaitResponse / Deploy DeviceApp and wait for response
** Insight
*** getImageData / Get saved images
**** Because the getImages gets up to 256 images, this API calls the getImages multiple times to cover up the restriction
*** getLastInferenceData / Get the latest saved inference results
*** getLastInferenceAndImageData / Get the latest saved inference results and images
**** Get images with the most recent date, find and return inference results tied to images

* Log to the console when the Console Access Library is running
** The log format is defined as follows
*** [Log time] [Log level] [Client name] : Message body
*** Log time uses the system time of user environment
*** Log time outputs date + time + time zone in ISO 8601 format
*** Sample log output: + 
2022-06-21T11:31:42.612+0900 ERROR ConsoleAccessClient : Failed to log request

** The log level can be switched
*** Log levels are defined as follows
+
[%header%autowidth]
|===
|Level |Summary 

|ERROR
|Use when the Console Access Library can't finish processing successfully

|WARNING
|Use when some unexpected problem occurs that is not necessarily an error but is also not normal

|INFO
|Use when the Console Access Library executes events

|DEBUG
|Use when outputting detailed debugging information, such as how the Console Access Library is working

|OFF
|Turn off all logging
|===
*** Output logs at or above a specified log level +
Example: Output INFO/WARNING/ERROR, not DEBUG when the specified log level is INFO
*** Do not output all log levels when the specified log level is OFF
*** Set the default log level to OFF
*** Log levels are specified in the procedure specified for each language by the application using the library.
+
[%header]
|===
|Example specification in TypeScript
a|
[source, TypeScript]
----
import { Logger } from 'consoleaccesslibrary';

# Set the desired logging level
Logger.setLogLevel("warning")
----
|===

* Check for error conditions when running the Console Access Library
** Judge as an error under the following conditions
*** Bad API input parameters
*** The API input parameters are good, but the response from the Console Low Level SDK is not as expected (such as timeout/error)
*** Unable to connect to the Console successfully (authentication error, wrong URL, etc.)

=== Algorithm
* Start to use the Console Access Library
. Cloud App creates a Config
+
. Cloud App creates a Client
+
Get an access token and generate the Low Level SDK during Client generation
. From the Client instance, use API wrapped around Low Level SDK API, and functional complex API (High Level API) 
+
Get and update an access token needed to access the Console using an API wrapped around Low Level SDK API
+
- The access token expires in 1 hour and is renewed if it expires in less than 180 seconds.

* Start to get inference result metadata - Stop
. Find the device ID using the `**getDevices**` API
. Start to get inference result metadata using the `**startUploadInferenceResult**` API
. Use the `**Insight**` API to get inference results and images
. Stop to get inference result metadata using the `**stopUploadInferenceResult**` API


=== Under what condition
* Use the Low Level SDK to access the Console REST API

=== API
* Config
** constructor(consoleEndpoint: string, portalAuthorizationEndpoint: string, clientId: string, clientSecret: string)

* Client
** constructor(configuration: Config)
** deviceManagement()
** aiModel()
** deployment()
** insight()

* DeviceManagement
** getDevices(deviceId?: string, deviceName?: string, connectionState?: string, deviceGroupId?: string)
** startUploadInferenceResult(deviceId: string)
** stopUploadInferenceResult(deviceId: string)
** getCommandParameterFile()

* AI Model
** importBaseModel(modelId: string, model: string, converted?: boolean, vendorName?: string, comment?: string, inputFormatParam?: string, networkConfig?: string, networkType?: string, labels?: Array<string>)
** getModels(modelId?: string, comment?: string, projectName?: string, modelPlatform?: string, projectType?: string, deviceId?: string, latestType?: string)
** getBaseModelStatus(modelId: string, latestType?: string)
** deleteModel(modelId: string)
** publishModel(modelId: string, deviceId?: string)

* AI Model High Level API
** publishModelWaitResponse(modelId: string, deviceId?: string, callback?: publishModelWaitResponseCallback)
*** publishModelWaitResponseCallback(status: string)

* Deployment
** importDeviceApp(compiledFlg: string, appName: string, versionNumber: string, fileName: string, fileContent: string, entryPoint?: string, comment?: string)
** getDeviceApps()
** deleteDeviceApp(appName: string, versionNumber: string)
** getDeployConfigurations()
** createDeployConfiguration(configId: string, comment?: string, sensorLoaderVersionNumber?: string, sensorVersionNumber?: string, modelId?: string, modelVersionNumber?: string, apFwVersionNumber?: string)
** deployByConfiguration(configId: string, deviceIds: string, replaceModelId?: string, comment?: string)
** getDeployHistory(deviceId: string)
** deleteDeployConfiguration(configId: string)
** cancelDeployment(deviceId: string, deployId: number)
** deployDeviceApp(appName: string, versionNumber: string, deviceIds: string, deployParameter?: string, comment?: string)
** undeployDeviceApp(deviceIds: string)
** getDeviceAppDeploys(appName: string, versionNumber: string)

* Deployment High Level API
** deployByConfigurationWaitResponse(configId: string, deviceIds: string, replaceModelId?: string, comment?: string, timeout?: number, callback?: deployByConfigurationWaitResponseCallback)
*** deployByConfigurationWaitResponseCallback(deviceStatusArray: object)
** deployDeviceAppWaitResponse(appName: string, versionNumber: string, deviceIds: string, deployParameter?: string, comment?: string, callback?: deployDeviceAppWaitResponseCallback)
*** deployDeviceAppWaitResponseCallback(deviceStatusArray: object)

* Insight
** getImageDirectories(deviceId?: string)
** getImages(deviceId: string, subDirectoryName: string, numberOfImages?: number, skip?: number, orderBy?: string)
** getInferenceResults(deviceId: string, filter?: string, numberOfInferenceResults?: number, raw?: number, time?: string)
** exportImages(key: string, fromDatetime?: string, toDatetime?: string, deviceId?: string, fileFormat?: string)

* Insight High Level API
** getImageData(deviceId: string, subDirectoryName: string, numberOfImages?: number, skip?: number, orderBy?: string)
** getLastInferenceData(deviceId: string)
** getLastInferenceAndImageData(deviceId: string, subDirectoryName: string)

=== Others exclusive conditions/Specifications
* Command parameter file has been applied to the edge AI device

== User interface specifications
* None

== API parameters in each block
Each error message has a different function name depending on the language (represented in this document by an error message in TypeScript).

* Config
** constructor
+
【Error: consoleEndpoint is empty】E001 : consoleEndpoint is required.
+
【Error: portalAuthorizationEndpoint is empty】E001 : portalAuthorizationEndpoint is required.
+
【Error: clientId is empty】E001 : clientId is required.
+
【Error: clientSecret is empty】E001 : clientSecret is required.
+
|===
|Parameter’s name|Meaning|Range of parameter

|consoleEndpoint
|URL to access the Console
|None +
If not specified, read from environment variable

|portalAuthorizationEndpoint
|URL to issue an access token needed to access the Console
|None +
If not specified, read from environment variable

|clientId
|Client ID needed to issue an access token
|None +
If not specified, read from environment variable

|clientSecret
|Client secret needed to issue an access token
|None +
If not specified, read from environment variable

|===
+
|===
|Return value|Meaning

|Config instance
|Config instance with information needed to access the Console
|===

* Client
** constructor
+
|===
|Parameter’s name|Meaning|Range of parameter

|configuration
|Config instance with information needed to access the Console
|None

|===
+
|===
|Return value|Meaning

|Client instance
|Client that can execute API wrapped around Low Level SDK API, and functional complex API (High Level API) instance
|===

** deviceManagement: Get the instance that provides DeviceManagement API
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|DeviceManagement instance
|Instance that provides DeviceManagement API
|===

** aiModel: Get the instance that provides AI Model API
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|AI Model instance
|Instance that provides AI Model API
|===

** deployment: Get the instance that provides Deployment API
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|Deployment instance
|Instance that provides Deployment API
|===

** insight: Get the instance that provides Insight API
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|Insight instance
|Instance that provides Insight API
|===

* DeviceManagement
** getDevices: Get edge AI device info list
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Partial search, case insensitive +
If not specified, search all deviceId

|deviceName
|Name of the edge AI device
|Partial search, case insensitive +
If not specified, search all deviceName

|connectionState
|Connection state
|Connected +
Disconnected +
Exact match search, case insensitive +
If not specified, search all connectionState

|deviceGroupId
|Affiliation group of the edge AI device
|Exact match search, case insensitive +
If not specified, search all deviceGroupId

|===
+
|===
|Return value|Meaning

|Device information
|Edge AI device information
|===

** startUploadInferenceResult: Start to upload inference results
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|===
+
|===
|Return value|Meaning

|result
|Execution result

|outputSubDirectory
|Input image save path、UploadMethod:Blob Storage only

|===

** stopUploadInferenceResult: Stop to upload inference results
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** getCommandParameterFile: Get list of command parameter files registered in the Console
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|result
|List of command parameter files registered in the Console

|===

* AI Model
** importBaseModel: Import base model
+
【Error: modelId is empty】E001 : modelId is required.
+
【Error: model is empty】E001 : model is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
[cols="1,2,2"]
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|Model ID(specify by new save or upgrade)
|100 characters or less +
Forbidden characters except for the following +
Half-width alphanumeric characters +
- Hyphen +
_ Underbar +
() Parenthesis +
. Dot

|model
|Model file SAS URI
|None

|converted
|Option to indicate converted
|True: Post-conversion model +
False: Pre-conversion model +
If not specified, False

|vendorName
|Vendor name（Specify by new save）
|100 characters or less +
Not specified in case of version upgrade +
If not specified, no vendor name

|comment
|Description of the model to enter when registering a new model +
Set as description of the model and version on new save +
Set as description of the version when upgrading +
|100 characters or less
If not specified, no description of the model to enter when registering a new model

|inputFormatParam
|URI of input format param file (json format) +
Evaluate the following +
Azure: SAS URI +
AWS:   Presigned URI +
Usage: Packager conversion information (image format information)
|Forbidden characters except SAS URI format +
Json format is an object array (each object contains the following values) +
Example: +
ordinal: Order of DNN input to converter (value range: 0 ~ 2) +
format: "RGB" or "BGR" +
If not specified, do not evaluate

|networkConfig
|URI of network config file in json format +
Evaluate the following +
Azure: SAS URI +
AWS:   Presigned URI +
Specify for a pre-conversion model(Ignore for a post-conversion model) +
Application: Conversion parameter information for the model converter
|Forbidden characters except SAS URI format +
If not specified, do not evaluate

|networkType
|Network type (specify only for new model registration)
|0: Custom Vision +
1: Non Custom Vision +
If not specified, 1


|labels
|Label name
|Example: ["label01","label02","label03"]

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** getModels: Get model info list
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|Model ID
|Partial search +
If not specified, search all modelId

|comment
|Model description
|Partial search +
If not specified, search all comment

|projectName
|Project name
|Partial search +
If not specified, search all projectName

|modelPlatform
|Model platform
|0 : Custom Vision +
1 : Non Custom Vision +
2 : Model Retrainer +
Exact match search +
If not specified, search all modelPlatform

|projectType
|Project type
|0 : Base project +
1 : Device project +
Exact match search +
If not specified, search all projectType

|deviceId
|Edge AI device ID (specify if you want to search for a device model)
|Exact match search +
Case sensitive +
If not specified, search all deviceId

|latestType
|Type of the latest version
|0 : Latest published version +
1 : Latest version, including during conversion/publishing +
Exact match search +
If not specified, 1

|===
+
|===
|Return value|Meaning

|Model information
|Same as return value name

|===

** getBaseModelStatus: Get base model status
+
【Error: modelId is empty】E001 : modelId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|Model ID
|None

|latestType
|Type of the latest version
|0 : Latest published version +
1 : Latest version, including during conversion/publishing +
Exact match search +
If not specified, 1

|===
+
|===
|Return value|Meaning

|Base model information
|Same as return value name

|===

** deleteModel: Delete model
+
【Error: modelId is empty】E001 : modelId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|Model ID
|None

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** publishModel: Publish model
+
【Error: modelId is empty】E001 : modelId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|Model ID
|None

|deviceId
|Edge AI device ID
|Case sensitive +
Specify for device models +
If the base model is the target, do not specify

|===
+
|===
|Return value|Meaning

|result
|Execution result

|importId
|Import ID

|===

** publishModelWaitResponse: Publish model and wait for response
+
【Error: modelId is empty】E001 : modelId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|modelId
|Model ID
|None

|deviceId
|Edge AI device ID
|Case sensitive +
Specify for device models +
If the base model is the target, do not specify

|callback
|Callback function
|Check the processing result with the getBaseModelStatus and call the callback function to notify the processing status
If not specified, no notification by the callback function

|===
+
|===
|Return value|Meaning

|result
|Execution result

|process time
|Processing time

|===

** publishModelWaitResponseCallback: Status notification callback function for the publishModelWaitResponse
+
|===
|Parameter’s name|Meaning|Range of parameter

|status
|Publish status
|'01': 'Before conversion' +
'02': 'Converting' +
'03': 'Conversion failed' +
'04': 'Conversion complete' +
'05': 'Adding to configuration' +
'06': 'Add to configuration failed' +
'07': 'Add to configuration complete' +
'11': 'Saving'(Model saving status for Model Retainer)
|===
+
|===
|Return value|Meaning

|-
|-

|===

* Deployment
** importDeviceApp: Import DeviceApp
+
【Error: compiledFlg is empty】E001 : compiledFlg is required.
+
【Error: appName is empty】E001 : appName is required.
+
【Error: versionNumber is empty】E001 : versionNumber is required.
+
【Error: fileName is empty】E001 : fileName is required.
+
【Error: fileContent is empty】E001 : fileContent is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
[cols="1,2,2"]
|===
|Parameter’s name|Meaning|Range of parameter

|compiledFlg
|Option to indicate compiled
|0:Not compiled(will be compiled) +
1:Compiled(will not be compiled)

|appName
|Name of the DeviceApp
|The maximum character limit is "appName + versionNumber <=31" +
Forbidden characters except for the following +
・Alphanumeric characters +
・Underbar +
・Dot

|versionNumber
|DeviceApp version
|The maximum character limit is "appName + versionNumber <=31" +
Forbidden characters except for the following +
・Alphanumeric characters +
・Underbar +
・Dot

|fileName
|Name of the DeviceApp file
|None

|fileContent
|File contents of the DeviceApp
|Base64 encoded string

|entryPoint
|EVP module entry point
|None +
If not specified, "ppl"

|comment
|Description of the DeviceApp
|100 characters or less +
If not specified, no comment

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** getDeviceApps: Get DeviceApp info list
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|DeviceApp information
|Same as return value name

|===

** deleteDeviceApp: Delete DeviceApp
+
【Error: appName is empty】E001 : appName is required.
+
【Error: versionNumber is empty】E001 : versionNumber is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|appName
|Name of the DeviceApp
|None

|versionNumber
|DeviceApp version
|None

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** getDeployConfigurations: Get deployment configuration list
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|Deployment configuration
|Same as return value name

|===

** createDeployConfiguration: Create deployment configuration
+
【Error: configId is empty】E001 : configId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|configId
|Config ID
|20 characters or less +
Forbidden characters except for the following +
Half-width alphanumeric characters +
- Hyphen +
_ Underbar +
() Parenthesis +
. Dot

|comment
|Config description
|100 characters or less +
If not specified, no comment

|sensorLoaderVersionNumber
|SensorLoader version number
|If -1 is specified, the default version (system setting "DVC0017") is applied +
If not specified, no SensorLoader deployment

|sensorVersionNumber
|Sensor version number
|If -1 is specified, the default version (system setting "DVC0018") is applied +
If not specified, no Sensor deployment

|modelId
|Model ID
|If not specified, no model deployment

|modelVersionNumber
|Model version number
|If not specified, the latest version applies

|apFwVersionNumber
|ApFw version number
|If not specified, no firmware deployment

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** deployByConfiguration: Deploy
+
【Error: configId is empty】E001 : configId is required.
+
【Error: deviceIds is empty】E001 : deviceIds is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|configId
|Config ID
|None

|deviceIds
|Edge AI device IDs
|Specify multiple edge AI device IDs separated by commas +
Case sensitive

|replaceModelId
|ID of the model being replaced
|Specify the modelId or networkId +
If the specified model ID is not in the DB, treat the input value as networkId (Console internal management ID) +
If not specified, do not replace.

|comment
|Deployment comment
|100 characters or less +
If not specified, no comment

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** getDeployHistory: Get deployment history
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|===
+
|===
|Return value|Meaning

|Deployment history
|Same as return value name

|===

** deleteDeployConfiguration: Delete deployment configuration
+
【Error: configId is empty】E001 : configId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|configId
|Config ID
|None

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** cancelDeployment: Force cancel deployment state
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: deployId is empty】E001 : deployId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|deployId
|Deploy ID
|ID that can be gotten using the getDeployHistory

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** deployDeviceApp: Deploy DeviceApp
+
【Error: appName is empty】E001 : appName is required.
+
【Error: versionNumber is empty】E001 : versionNumber is required.
+
【Error: deviceIds is empty】E001 : deviceIds is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|appName
|App name
|None

|versionNumber
|App version
|None

|deviceIds
|Edge AI device IDs
|Specify multiple edge AI device IDs separated by commas +
Case sensitive

|deployParameter
|Deploy parameters
|A Base64 encoded string in Json format +
If not specified, no parameter

|comment
|Deployment comment
|100 characters or less +
If not specified, no comment

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** undeployDeviceApp: Undeploy DeviceApp
+
【Error: deviceIds is empty】E001 : deviceIds is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceIds
|Edge AI device ID
|Specify multiple edge AI device IDs separated by commas +
Case sensitive

|===
+
|===
|Return value|Meaning

|result
|Execution result

|===

** getDeviceAppDeploys: Get DeviceApp deployment history
+
【Error: appName is empty】E001 : appName is required.
+
【Error: versionNumber is empty】E001 : versionNumber is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|appName
|App name
|None

|versionNumber
|App version
|None

|===
+
|===
|Return value|Meaning

|DeviceApp deployment history
|Same as return value name

|===

** deployByConfigurationWaitResponse: Deploy and wait for response
+
【Error: configId is empty】E001 : configId is required.
+
【Error: deviceIds is empty】E001 : deviceIds is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|configId
|Config ID
|None

|deviceIds
|Edge AI device IDs
|Specify multiple edge AI device IDs separated by commas +
Case sensitive

|replaceModelId
|ID of the model being replaced
|Specify the modelId or networkId +
If the specified model ID is not in the DB, treat the input value as networkId (Console internal management ID) +
If not specified, do not replace.

|comment
|Deployment comment
|100 characters or less +
If not specified, do not replace

|timeout
|timeout waiting for completion +
Set the timeout to exit the deployment process because it may remain in progress, such as when edge AI device hangs.
|None +
If not specified, 3600 seconds

|callback
|Callback function +
Check the processing result with the getDeployHistory and call the callback function to notify the processing status
|If not specified, no notification by the callback function

|===
+
|===
|Return value|Meaning

|result
|Execution result

|process time
|Processing time

|===

** deployByConfigurationWaitResponseCallback: Status notification callback function for the deployByConfigurationWaitResponse
+
[cols="1,1,2"]
|===
|Parameter’s name|Meaning|Range of parameter

|deviceStatusArray
|List of deployment state of edge AI devices
|The format is as follows: +
[ +
　{ +
　　<deviceId>: { +
　　　"status":<status> +
　　} +
　}, +
] +

Fill in data for deviceId specified by deviceIds in devloyByConfigurationWaitResponse +

<deviceId>: Edge AI device ID +
<status>: Fill in the following deployment states +
　0: Deploying +
　1: Success +
　2: Failure +
　3: Cancel +
　9: DeviceApp is undeployed

|===
+
|===
|Return value|Meaning

|-
|-

|===

** deployDeviceAppWaitResponse: Deploy DeviceApp and wait for response
+
【Error: appName is empty】E001 : appName is required.
+
【Error: versionNumber is empty】E001 : versionNumber is required.
+
【Error: deviceIds is empty】E001 : deviceIds is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|appName
|App name
|None

|versionNumber
|App version
|None

|deviceIds
|Edge AI device IDs
|Specify multiple edge AI device IDs separated by commas +
Case sensitive

|deployParameter
|Deploy parameters
|A Base64 encoded string in Json format +
If not specified, no parameter

|comment
|Deployment comment
|100 characters or less +
If not specified, no comment

|callback
|Callback function +
Check the processing result with the getDeviceAppDeploys and call the callback function to notify the processing status
|If not specified, no notification by the callback function

|===
+
|===
|Return value|Meaning

|result
|Execution result

|process time
|Processing time

|===

** deployDeviceAppWaitResponseCallback: Status notification callback function for the deployDeviceAppWaitResponse
+
[cols="1,1,2"]
|===
|Parameter’s name|Meaning|Range of parameter

|deviceStatusArray
|List of deployment state of edge AI devices
|The format is as follows: +
[ +
　{ +
　　<deviceId>: { +
　　　"status":<status>, +
　　　"found_position":<found_position>, +
　　　"skip":<skip> +
　　} +
　}, +
] +

Fill in data for deviceId specified by deviceIds in deployDeviceAppWaitResponse +

<deviceId>: Edge AI device ID +
<found_position>: Index of the deviceId stored in the getDeviceAppDeploys response +
<skip>: Fill in the following values +
　0: For the most recent status stored in the getDeviceAppDeploys response +
　1: For the non-most recent status stored in the getDeviceAppDeploys response +
<status>: Fill in the following deployment states +
　0: Deploying +
　1: Success +
　2: Failure +
　3: Cancel +

|===
+
|===
|Return value|Meaning

|-
|-

|===

* Insight
** getImageDirectories: Get image save directory list
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive +
If not specified, return information for all deviceIds

|===
+
|===
|Return value|Meaning

|Image save directory information
|Same as return value name
|===

** getImages: Get saved images
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: subDirectoryName is empty】E001 : subDirectoryName is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|subDirectoryName
|Image save subdirectory
|None +
The subdirectory is either the directory notified in the response to the startUploadInferenceResult or the directory gotten by the getImageDirectories

|numberOfImages
|Number of images to get
|0-256 +
If not specified:50

|skip
|Number of images to skip getting
|None +
If not specified:0

|orderBy
|Sort order: Sort order by date and time the image was created
|DESC、ASC、desc、asc +
If not specified:ASC

|===
+
|===
|Return value|Meaning

|Total image count
|Same as return value name

|Image file name and image file data
|Same as return value name, image data is Base64 encoded
|===

** getInferenceResults: Get list of saved inference result metadata
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
[cols="1,2,2"]
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|filter
|Search filter (same specifications as Cosmos DB UI in Azure portal except for the following)) +
- The where string need not be prepended +
- No need to attach deviceId
|None

|numberOfInferenceResults
|Number of inference results gotten
|None +
If not specified:20

|raw
|Data format of inference results
|1:Append records as they are saved in Cosmos DB +
0:Do not append +
If not specified:1

|time
|Timestamp of the inference results saved in Cosmos DB
|yyyyMMddHHmmssfff +
- yyyy: 4-digit string of the year +
- MM: 2-digit string of the month +
- dd: 2-digit string of the day +
- HH: 2-digit string of the time +
- mm: 2-digit string of the minute +
- ss: 2-digit string of the second +
- fff: 3-digit string of the millisecond

|===
+
|===
|Return value|Meaning

|Inference results
|Same as return value name
|===

** exportImages: Export saved images
+
【Error: key is empty】E001 : key is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|key
|RSA public key
|Base64 encoded string

|fromDatetime
|Date and time(From)
|yyyyMMddhhmm format +
If not specified, no start date and time is set

|toDatetime
|Date and time(To)
|yyyyMMddhhmm format +
If not specified, no end date and time is set

|deviceId
|Edge AI device ID
|Case sensitive +
If not specified, specify all deviceId

|fileFormat
|Image file format
|JPG, BMP, RAW +
If not specified, specify all file format

|===
+
|===
|Return value|Meaning

|key
|Common key +
A common key for decrypting images encrypted with a public key

|url
|SUS URI for download

|===

** getImageData: Get saved images
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: subDirectoryName is empty】E001 : subDirectoryName is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|subDirectoryName
|Image save subdirectory
|None +
The subdirectory is either the directory notified in the response to the startUploadInferenceResult or the directory gotten by the getImageDirectories

|numberOfImages
|Number of images to get
|None +
If not specified:50

|skip
|Number of images to skip getting
|None +
If not specified:0

|orderBy
|Sort order: Sort order by date and time the image was created
|DESC、ASC、desc、asc +
If not specified:ASC

|===
+
|===
|Return value|Meaning

|Total image count
|Same as return value name

|Image file name and image file data
|Same as return value name, image data is Base64 encoded
|===

** getLastInferenceData: Get the latest saved inference results
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|===
+
|===
|Return value|Meaning

|Inference results
|Same as return value name
|===

** getLastInferenceAndImageData(): Get the latest saved inference results and images
+
【Error: deviceId is empty】E001 : deviceId is required.
+
【Error: subDirectoryName is empty】E001 : subDirectoryName is required.
+
【Error: When an error occurs in the Low Level SDK】Raise an error defined in the Console Access Library
+
【Error: When http_status returned from Low Level SDK API is not 200】Raise an error defined in the Console Access Library
+
|===
|Parameter’s name|Meaning|Range of parameter

|deviceId
|Edge AI device ID
|Case sensitive

|subDirectoryName
|Image save subdirectory
|None +
The subdirectory is either the directory notified in the response to the startUploadInferenceResult or the directory gotten by the getImageDirectories

|===
+
|===
|Return value|Meaning

|Inference results and image data
|Same as return value name, image data is Base64 encoded
|===

== Log output messages
The messages to be displayed for each level are defined as follows

=== ERROR level
[%header%autowidth]
|===
|MessageID |Conditions |Message |Parameter
|E001
|Output when a required parameter is not passed
|{0} is required.
|{0}:Parameter name not passed
|===

=== WARNING level
[%header%autowidth]
|===
|MessageID |Conditions |Message |Parameter
|W001
|Output when calling a deprecated class or function
|{0} has been deprecated.
|{0}:Name of the called class or function
|===

=== INFO level
T.B.D.

=== DEBUG level
T.B.D.

== Target performances/Impact on performances
* None

== Assumption/Restriction
* None

== Remarks
* None

== Unconfirmed items
* None
